/**
 * Action types for invites actions.
 */
export const GET_INVITES_REQUEST = 'GET_INVITES_REQUEST';
export const GET_INVITES_REQUEST_SUCCESS = 'GET_INVITES_REQUEST_SUCCESS';
export const GET_INVITES_REQUEST_FAILURE = 'GET_INVITES_REQUEST_FAILURE';

/**
 * Action types for add invites actions.
 */
export const ADD_INVITES_REQUEST = 'ADD_INVITES_REQUEST';
export const ADD_INVITES_REQUEST_SUCCESS = 'ADD_INVITES_REQUEST_SUCCESS';
export const ADD_INVITES_REQUEST_FAILURE = 'ADD_INVITES_REQUEST_FAILURE';

/**
 * Action types for delete invites actions.
 */
export const DELETE_INVITES_REQUEST = 'DELETE_INVITES_REQUEST';
export const DELETE_INVITES_REQUEST_SUCCESS = 'DELETE_INVITES_REQUEST_SUCCESS';
export const DELETE_INVITES_REQUEST_FAILURE = 'DELETE_INVITES_REQUEST_FAILURE';
